chore(tests): skip flaky "detects invalid PEM key passphrase" test (#17413)
Skips flaky test:

```
  1) lib/client-certificates loads cert files detects invalid PEM key passphrase:

      AssertionError: expected [Function: act] to throw error including 'Cannot decrypt PEM key with supplied passphrase (check the passphrase file content and that it doesn\'t have unexpected whitespace at the end)' but got 'Failed to load client certificates for clientCertificates[0]: Cannot parse PEM key: Only 8, 16, 24, or 32 bits supported: 352.  For more debug details run Cypress with DEBUG=cypress:server:client-certificates*'
      + expected - actual

      -Failed to load client certificates for clientCertificates[0]: Cannot parse PEM key: Only 8, 16, 24, or 32 bits supported: 352.  For more debug details run Cypress with DEBUG=cypress:server:client-certificates*
      +Cannot decrypt PEM key with supplied passphrase (check the passphrase file content and that it doesn't have unexpected whitespace at the end)
      
      at Context.<anonymous> (test/unit/client_certificates_spec.ts:386:47)
      at processImmediate (internal/timers.js:462:21)
```

https://app.circleci.com/pipelines/github/cypress-io/cypress/22260/workflows/043dddbc-1095-4a98-bd32-3606e59e65ce/jobs/816365

It seems to be a race condition, but I can't pin down where. Everything is synchronous...

cc @GCHQDeveloper911