bundle: adding more externals
- at this point a bundle is generated that needs to have some winston references removed
- once that is done it at least loads, but even when run with cypress will raise the following error

```
Launcher project exports
{
  launch: [Function: launch],
  detect: [Function],
  detectByPath: [Function]
}
⛔️ please use it as a module, not from CLI
TypeError: Not running in an Electron environment!
    at Object.<anonymous> (/Volumes/d/dev/cy/perf-tr1/cypress/dist/darwin/bundle.js:141360:8)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Object.<anonymous> (electron/js2c/browser_init.js:205:3373)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:205:3577)
    at __webpack_require__ (electron/js2c/browser_init.js:1:128)
    at electron/js2c/browser_init.js:1:1200
    at electron/js2c/browser_init.js:1:1267
    at NativeModule.compile (internal/bootstrap/loaders.js:287:5)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:222:8)
    at loadNativeModule (internal/modules/cjs/helpers.js:23:9)
    at Module._load (internal/modules/cjs/loader.js:698:15)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1056:10)
    at internal/main/run_main_module.js:17:11
```